server:
  port: 8086
logging:
  level:
    com.megumi.hospitalregistersystem.dao: DEBUG
spring:
  datasource:
    url: jdbc:mysql://117.50.163.249:3306/register_management?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: hzau.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl